/** Spacing scale reused by the layout / spacer fields (ported from the Puck demo). */
export const spacingOptions = [
  { label: '0.5rem', value: '0.5rem' },
  { label: '1rem', value: '1rem' },
  { label: '1.5rem', value: '1.5rem' },
  { label: '2rem', value: '2rem' },
  { label: '2.5rem', value: '2.5rem' },
  { label: '3rem', value: '3rem' },
  { label: '3.5rem', value: '3.5rem' },
  { label: '4rem', value: '4rem' },
  { label: '4.5rem', value: '4.5rem' },
  { label: '5rem', value: '5rem' },
  { label: '5.5rem', value: '5.5rem' },
  { label: '6rem', value: '6rem' },
  { label: '6.5rem', value: '6.5rem' },
  { label: '7rem', value: '7rem' },
  { label: '7.5rem', value: '7.5rem' },
  { label: '8rem', value: '8rem' },
  { label: '8.5rem', value: '8.5rem' },
  { label: '9rem', value: '9rem' },
  { label: '9.5rem', value: '9.5rem' },
  { label: '10rem', value: '10rem' },
];
