# Generated by Django 6.0.7 on 2026-07-15 03:50

import django.db.models.deletion
import wagtail.contrib.puck.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_revisablecluster_revisableclusterchild'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuckTestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('puck_body', wagtail.contrib.puck.fields.PuckField(blank=True, default=wagtail.contrib.puck.fields.default_puck_document)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
